### ISSUE TITLE
This is not an issue but rather a way to contact you.

### ISSUE THREAD

**Issue by T3M1N4L** [Metro420yt/yuji-crx#3]
I have seen your comfytheme repository and the classupdate stuff. I have my own theme repo (which is a fork of comfy @ [https://github.com/t3m1n4l/amoled-comfy/](https://github.com/t3m1n4l/amoled-comfy/)) I want to create a workflow that would automatically update the classes using the python script, and I alredy created one which I think would work. I came here to ask you if you are using any workflows to automate your ClassUpdate, and for you to see if you could check my classupdate automation to see if it works.

I'm kind of a newbie as this is my first time working with workflows.

**Comment by Metro420yt** [comment]
im not using a workflow, just an [npm script](https://github.com/Metro420yt/Discord-comfy/blob/e180d72c83ff2d918a6231294b9f91e6b3bdd9d0/package.json#L10) (good idea though)

just looking at it, my ClassUpdate is modified for continuous integration, so im not sure if [this line](https://github.com/T3M1N4L/AMOLED-comfy/blob/6bd860285b93f7d10ba5209556061638ac051452/.github/workflows/actions.yml#L24) will work
as for the rest of it, looks fine, but i cant really comment since i use [EndBug/add-and-commit](https://github.com/EndBug/add-and-commit) to push

also, you can run workflows locally with [nektos/act](https://github.com/nektos/act), but i was having issues with getting python setup (should be fine on github runners though)

**Comment by T3M1N4L** [comment]
Do you automate the NPM script? or Is it even possible to edit the npm script? I'm pretty sure it's possible, I'll look into it when I have free time

**Comment by T3M1N4L** [comment]
I tried using your version of classupdate, and this is what I got 
```bash
@T3M1N4L ➜ /workspaces/AMOLED-comfy (main) $ npm run class

> AMOLED-comfy@2.4.2 class
> cd ./ClassUpdate && python ./replace.py LOCAL -y

==== ClassUpdate by Saltssaumure ====

Traceback (most recent call last):
  File "/workspaces/AMOLED-comfy/ClassUpdate/./replace.py", line 15, in <module>
    use_local_diff, diff_location, css_filenames = get_params()
                                                   ^^^^^^^^^^^^
  File "/workspaces/AMOLED-comfy/ClassUpdate/lib/input.py", line 54, in get_params
    config = get_config("config.ini")
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/AMOLED-comfy/ClassUpdate/lib/input.py", line 41, in get_config
    config_user = raw_config[profile]
                  ~~~~~~~~~~^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'LOCAL'
```

Any Idea how to fix it?

**Comment by Metro420yt** [comment]
the config names are capital sensitive (im pretty sure), you passed "LOCAL" and your [config.ini](https://github.com/T3M1N4L/AMOLED-comfy/blob/main/ClassUpdate%2Fconfig.ini#L7) is lowercase

**Comment by T3M1N4L** [comment]
Yeah lol, it seems to have been fixed. A slight overlook by me 😅 lol. 
![image](https://github.com/user-attachments/assets/62c13ad1-086e-447f-abb5-2c7d53d2b362)
For some reason I still keep on getting pycahce files even though my gitignore looks like this
```
prepros.config
/.vscode/
sass.txt
.prettierignore
CHECKUP.txt
node_modules
dist
.parcel-cache
package-lock.json
*.pyc
__pycache__/
ClassUpdate/__pycache__/

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

prepros.config
/.vscode/
sass.txt
.prettierignore
CHECKUP.txt
node_modules
dist
.parcel-cache
package-lock.json
*.pyc
```

any idea why?
I checked on stackoverflow, but from what I see no one else has this issue.
What did you do to make pycache not generate?

**Comment by Metro420yt** [comment]
pycache will always generate when running python, but it wont get pushed if in .gitignore
[this answer](https://stackoverflow.com/a/16869074/19807043) further explains

**Comment by T3M1N4L** [comment]
OH! thanks for telling me that! I didn't know that lol

Also looks like I got it to work, the classupdate with github workflows!
![image](https://github.com/user-attachments/assets/54c0dc40-1b75-4f5c-80bd-c5e533244603)

All I had to change was convert what I had to what *you* had in npm script for class updates! 
```
      - name: execute py script # run replace.py
        run: |
           cd ./ClassUpdate && python ./replace.py DEFAULT -y
```

You should add this workflow thing to your fork of classupdate and hope it gets accepted!
I'm pretty sure this is the first time automating classupdate lol
